#!/usr/bin/env python
# Nouhaila is a Web Applications Security Scanner
# By Nouhaila - facebook/100013898196018
# First demo conducted 12Apr-2014 @OWASP Chapter Egypt
# https://www.facebook.com/100013898196018